---
apiVersion: v1
kind: Namespace
metadata:
  name: system
  labels:
    name: system
    env: jarvis
---
apiVersion: v1
kind: Namespace
metadata:
  name: llm
  labels:
    name: llm
    env: jarvis
---
apiVersion: v1
kind: Namespace
metadata:
  name: monitoring
  labels:
    name: monitoring
    env: jarvis
---
apiVersion: v1
kind: Namespace
metadata:
  name: apps
  labels:
    name: apps
    env: jarvis
